line-length = 88

[lint]
select = ["C", "E", "F", "B", "B9", "UP", "I", "NPY201"]
ignore = [
    "E203",
    "E266",
    "W",
    "E501",
    "E731",
    "E741",
    "B006",  # Do not use mutable data structures for argument defaults
    "B007",  # Loop control variable `X` not used within loop body
    "B015",  # Pointless comparison. Did you mean to assign a value? Otherwise, prepend `assert` or remove it.
    "B018",  # Found useless expression. Either assign it to a variable or remove it.
    "B028",  # No explicit `stacklevel` keyword argument found
    "B904",  # Within an `except` clause, raise exceptions with `raise ... from err` or `raise ... from None` to distinguish them from errors in exception handling
    "C408",  # Unnecessary `dict` call (rewrite as a literal)
    "C416",  # Unnecessary `list` comprehension (rewrite using `list()`)
    "C419",  # Unnecessary list comprehension
    "UP031", # Use format specifiers instead of percent format
]

[lint.isort]
known-first-party = ["phidl"]

[lint.mccabe]
max-complexity = 18

[lint.per-file-ignores]
"*__init__.py" = ["E402"]
