{% set name = "phidl" %}
{% set version = "1.4.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/phidl-{{ version }}.tar.gz
  sha256: b2b1b9bd6d92fac6fc1028a69d410e220e712785e13ef6286a162c2a8976881f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - gdspy >=1.5
    - matplotlib-base
    - numpy
    - python
    - six

test:
  imports:
    - phidl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/phidl/
  summary: PHIDL
  license_file: MIT

